CRITICAL - 2024-10-31 15:04:46 --> ErrorException: Undefined property: stdClass::$money_requestsId
in APPPATH\Controllers\Home.php on line 95.
 1 APPPATH\Controllers\Home.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$money_requestsId', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php', 95)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->acceptRequest()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:04:57 --> ErrorException: Undefined property: stdClass::$money_requestsId
in APPPATH\Controllers\Home.php on line 95.
 1 APPPATH\Controllers\Home.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$money_requestsId', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php', 95)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->acceptRequest()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:04:59 --> ErrorException: Undefined property: stdClass::$money_requestsId
in APPPATH\Controllers\Home.php on line 95.
 1 APPPATH\Controllers\Home.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$money_requestsId', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php', 95)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->acceptRequest()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:05:00 --> ErrorException: Undefined property: stdClass::$money_requestsId
in APPPATH\Controllers\Home.php on line 95.
 1 APPPATH\Controllers\Home.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$money_requestsId', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php', 95)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->acceptRequest()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:05:01 --> ErrorException: Undefined property: stdClass::$money_requestsId
in APPPATH\Controllers\Home.php on line 95.
 1 APPPATH\Controllers\Home.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$money_requestsId', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php', 95)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->acceptRequest()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
ERROR - 2024-10-31 15:05:07 --> mysqli_sql_exception: Unknown column 'status' in 'field list' in C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `money_r...', 0)
#1 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `money_r...')
#2 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `money_r...')
#3 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseBuilder.php(2469): CodeIgniter\Database\BaseConnection->query('UPDATE `money_r...', Array, false)
#4 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
#5 C:\laragon\www\CAPSTONEBACKEND\system\BaseModel.php(987): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(807): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(129): CodeIgniter\Model->update('31', Array)
#8 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(941): App\Controllers\Home->rejectRequest()
#9 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\CAPSTONEBACKEND\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\CAPSTONEBACKEND\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-10-31 15:05:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'status' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2469): CodeIgniter\Database\BaseConnection->query('UPDATE `money_requests` SET `status` = :status:
WHERE `money_requests`.`id` IN :money_requests.id:', [...], false)
 2 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Home.php(129): CodeIgniter\Model->update('31', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->rejectRequest()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:05:07 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'status' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `money_requests` SET `status` = \'rejected\'
WHERE `money_requests`.`id` IN (\'31\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `money_requests` SET `status` = \'rejected\'
WHERE `money_requests`.`id` IN (\'31\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2469): CodeIgniter\Database\BaseConnection->query('UPDATE `money_requests` SET `status` = :status:
WHERE `money_requests`.`id` IN :money_requests.id:', [...], false)
 4 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Home.php(129): CodeIgniter\Model->update('31', [...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->rejectRequest()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:05:07 --> [Caused by] mysqli_sql_exception: Unknown column 'status' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `money_requests` SET `status` = \'rejected\'
WHERE `money_requests`.`id` IN (\'31\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `money_requests` SET `status` = \'rejected\'
WHERE `money_requests`.`id` IN (\'31\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `money_requests` SET `status` = \'rejected\'
WHERE `money_requests`.`id` IN (\'31\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2469): CodeIgniter\Database\BaseConnection->query('UPDATE `money_requests` SET `status` = :status:
WHERE `money_requests`.`id` IN :money_requests.id:', [...], false)
 5 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Home.php(129): CodeIgniter\Model->update('31', [...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->rejectRequest()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:06:16 --> ErrorException: Undefined property: stdClass::$money_requestsId
in APPPATH\Controllers\Home.php on line 95.
 1 APPPATH\Controllers\Home.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$money_requestsId', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php', 95)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->acceptRequest()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:10:12 --> ErrorException: Undefined property: stdClass::$money_requestsId
in APPPATH\Controllers\Home.php on line 95.
 1 APPPATH\Controllers\Home.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$money_requestsId', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php', 95)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->acceptRequest()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:10:13 --> ErrorException: Undefined property: stdClass::$money_requestsId
in APPPATH\Controllers\Home.php on line 95.
 1 APPPATH\Controllers\Home.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$money_requestsId', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php', 95)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->acceptRequest()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:10:13 --> ErrorException: Undefined property: stdClass::$money_requestsId
in APPPATH\Controllers\Home.php on line 95.
 1 APPPATH\Controllers\Home.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$money_requestsId', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php', 95)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->acceptRequest()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:29:56 --> ParseError: syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\Home.php on line 122.
 1 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\Home', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:30:09 --> ParseError: syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\Home.php on line 122.
 1 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\Home', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:30:21 --> ParseError: syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\Home.php on line 122.
 1 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\Home.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\Home', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
ERROR - 2024-10-31 15:39:47 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`researchcapstone`.`money_requests`, CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `mo...', 0)
#1 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `mo...')
#2 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `mo...')
#3 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mo...', Array, false)
#4 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\CAPSTONEBACKEND\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(25): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
#9 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\CAPSTONEBACKEND\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\CAPSTONEBACKEND\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-10-31 15:39:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`researchcapstone`.`money_requests`, CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (:reason:, :amount:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Home.php(25): CodeIgniter\Model->insert(Object(stdClass))
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:39:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`researchcapstone`.`money_requests`, CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (:reason:, :amount:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Home.php(25): CodeIgniter\Model->insert(Object(stdClass))
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:39:47 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`researchcapstone`.`money_requests`, CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (:reason:, :amount:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Home.php(25): CodeIgniter\Model->insert(Object(stdClass))
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
ERROR - 2024-10-31 15:39:56 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`researchcapstone`.`money_requests`, CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `mo...', 0)
#1 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `mo...')
#2 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `mo...')
#3 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `mo...', Array, false)
#4 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\CAPSTONEBACKEND\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(25): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
#9 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\CAPSTONEBACKEND\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\CAPSTONEBACKEND\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#13 {main}
CRITICAL - 2024-10-31 15:39:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`researchcapstone`.`money_requests`, CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (:reason:, :amount:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Home.php(25): CodeIgniter\Model->insert(Object(stdClass))
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:39:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`researchcapstone`.`money_requests`, CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (:reason:, :amount:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Home.php(25): CodeIgniter\Model->insert(Object(stdClass))
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 15:39:56 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`researchcapstone`.`money_requests`, CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (\'sdadad\', 400)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `money_requests` (`reason`, `amount`) VALUES (:reason:, :amount:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Home.php(25): CodeIgniter\Model->insert(Object(stdClass))
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:00:58 --> ParseError: syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\UserController.php on line 208.
 1 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\UserController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\UserController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\UserController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:02:12 --> ParseError: syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\UserController.php on line 208.
 1 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\UserController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\UserController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\UserController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:02:21 --> ParseError: syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\UserController.php on line 208.
 1 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\UserController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\UserController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\UserController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:03:56 --> ParseError: syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\UserController.php on line 208.
 1 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\UserController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\UserController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\UserController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:05:03 --> ParseError: syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\UserController.php on line 208.
 1 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\UserController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\UserController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\UserController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:05:13 --> ParseError: syntax error, unexpected token "public", expecting end of file
in APPPATH\Controllers\UserController.php on line 208.
 1 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\UserController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\UserController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\UserController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:10:54 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:12:02 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:16:41 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:19:57 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:20:19 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:23:49 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
ERROR - 2024-10-31 16:26:01 --> mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist in C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `no...', 0)
#1 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `no...')
#2 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `no...')
#3 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `no...', Array, false)
#4 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\CAPSTONEBACKEND\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(211): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance ...')
#9 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
#10 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\CAPSTONEBACKEND\public\index.php(85): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\CAPSTONEBACKEND\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2024-10-31 16:26:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:01\', \'2024-10-31 16:26:01\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:01\', \'2024-10-31 16:26:01\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:01 --> [Caused by] mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:01\', \'2024-10-31 16:26:01\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:01\', \'2024-10-31 16:26:01\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:01\', \'2024-10-31 16:26:01\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
ERROR - 2024-10-31 16:26:04 --> mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist in C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `no...', 0)
#1 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `no...')
#2 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `no...')
#3 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `no...', Array, false)
#4 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\CAPSTONEBACKEND\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(211): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance ...')
#9 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
#10 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\CAPSTONEBACKEND\public\index.php(85): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\CAPSTONEBACKEND\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2024-10-31 16:26:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:04 --> [Caused by] mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
ERROR - 2024-10-31 16:26:04 --> mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist in C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `no...', 0)
#1 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `no...')
#2 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `no...')
#3 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `no...', Array, false)
#4 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\CAPSTONEBACKEND\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(211): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance ...')
#9 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
#10 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\CAPSTONEBACKEND\public\index.php(85): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\CAPSTONEBACKEND\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2024-10-31 16:26:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:04 --> [Caused by] mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:04\', \'2024-10-31 16:26:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
ERROR - 2024-10-31 16:26:47 --> mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist in C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `no...', 0)
#1 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `no...')
#2 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `no...')
#3 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `no...', Array, false)
#4 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\CAPSTONEBACKEND\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(211): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance ...')
#9 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
#10 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\CAPSTONEBACKEND\public\index.php(85): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\CAPSTONEBACKEND\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2024-10-31 16:26:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:47\', \'2024-10-31 16:26:47\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:47\', \'2024-10-31 16:26:47\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:47 --> [Caused by] mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:47\', \'2024-10-31 16:26:47\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:47\', \'2024-10-31 16:26:47\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:47\', \'2024-10-31 16:26:47\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
ERROR - 2024-10-31 16:26:51 --> mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist in C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `no...', 0)
#1 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `no...')
#2 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `no...')
#3 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `no...', Array, false)
#4 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\CAPSTONEBACKEND\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(211): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance ...')
#9 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
#10 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\CAPSTONEBACKEND\public\index.php(85): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\CAPSTONEBACKEND\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2024-10-31 16:26:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:51\', \'2024-10-31 16:26:51\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:51\', \'2024-10-31 16:26:51\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:51 --> [Caused by] mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:51\', \'2024-10-31 16:26:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:51\', \'2024-10-31 16:26:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:51\', \'2024-10-31 16:26:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
ERROR - 2024-10-31 16:26:52 --> mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist in C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\CAPSTONEBACKEND\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `no...', 0)
#1 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `no...')
#2 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `no...')
#3 C:\laragon\www\CAPSTONEBACKEND\system\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `no...', Array, false)
#4 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\CAPSTONEBACKEND\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\CAPSTONEBACKEND\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(211): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\CAPSTONEBACKEND\app\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance ...')
#9 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
#10 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 C:\laragon\www\CAPSTONEBACKEND\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\CAPSTONEBACKEND\public\index.php(85): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\CAPSTONEBACKEND\system\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\...')
#14 {main}
CRITICAL - 2024-10-31 16:26:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:52\', \'2024-10-31 16:26:52\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:52\', \'2024-10-31 16:26:52\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:26:52 --> [Caused by] mysqli_sql_exception: Table 'researchcapstone.notifications' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:52\', \'2024-10-31 16:26:52\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:52\', \'2024-10-31 16:26:52\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (\'assistance\', \'New assistance request received\', 0, \'2024-10-31 16:26:52\', \'2024-10-31 16:26:52\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2302): CodeIgniter\Database\BaseConnection->query('INSERT INTO `notifications` (`type`, `message`, `is_read`, `created_at`, `updated_at`) VALUES (:type:, :message:, :is_read:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Home.php(211): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(38): App\Controllers\Home->createNotification('assistance', 'New assistance request received')
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Home->requestMoney()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:28:02 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:28:09 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:28:30 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:33:31 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:38:59 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 16:39:21 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 17:03:26 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 17:03:27 --> Error: Class "App\Models\ScheduleModel" not found
in APPPATH\Controllers\Home.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\Home->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 17:05:26 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 17:05:27 --> ErrorException: Namespace declaration statement has to be the very first statement or after any declare call in the script
in APPPATH\Models\ScheduleModel.php on line 6.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-10-31 17:06:10 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 17:06:35 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 17:07:25 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 17:13:32 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
CRITICAL - 2024-10-31 17:17:41 --> ErrorException: Undefined array key "expiresAt"
in APPPATH\Controllers\UserController.php on line 200.
 1 APPPATH\Controllers\UserController.php(200): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "expiresAt"', 'C:\\laragon\\www\\CAPSTONEBACKEND\\app\\Controllers\\UserController.php', 200)
 2 APPPATH\Controllers\UserController.php(173): App\Controllers\UserController->isValidSession('')
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserController->verifySession()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\laragon\\www\\CAPSTONEBACKEND\\public\\index.php')
